<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS version="2.1" language="zh_CN">
<context>
    <name>LogViewerWidget</name>
    <message>
        <location filename="../Qt/Core/Resources/UI/pqLogViewerWidget.ui" line="16"/>
        <source>Form</source>
        <translation>表单</translation>
    </message>
    <message>
        <location filename="../Qt/Core/Resources/UI/pqLogViewerWidget.ui" line="46"/>
        <source>Set filter on this log</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../Qt/Core/Resources/UI/pqLogViewerWidget.ui" line="56"/>
        <source>Show/hide all columns</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../Qt/Core/Resources/UI/pqLogViewerWidget.ui" line="59"/>
        <source>...</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../Qt/Core/Resources/UI/pqLogViewerWidget.ui" line="107"/>
        <source>Select rows above to show raw log text here. Save text with the Export Log button below.</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../Qt/Core/Resources/UI/pqLogViewerWidget.ui" line="131"/>
        <source>Export Log</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>OutputWidget</name>
    <message>
        <location filename="../Qt/Core/Resources/UI/pqOutputWidget.ui" line="16"/>
        <source>Form</source>
        <translation>表单</translation>
    </message>
    <message>
        <location filename="../Qt/Core/Resources/UI/pqOutputWidget.ui" line="73"/>
        <source>Show full messages</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../Qt/Core/Resources/UI/pqOutputWidget.ui" line="70"/>
        <source>Check to see raw messages generated by the application</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../Qt/Core/Resources/UI/pqOutputWidget.ui" line="80"/>
        <source>If unchecked and the window is closed, the window will remain closed when new messages are available.</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../Qt/Core/Resources/UI/pqOutputWidget.ui" line="83"/>
        <source>Always open for new messages</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../Qt/Core/Resources/UI/pqOutputWidget.ui" line="93"/>
        <source>Copy to Clipboard</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../Qt/Core/Resources/UI/pqOutputWidget.ui" line="100"/>
        <source>Save to File...</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../Qt/Core/Resources/UI/pqOutputWidget.ui" line="107"/>
        <source>Filter Messages</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../Qt/Core/Resources/UI/pqOutputWidget.ui" line="114"/>
        <source>Clear</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>PluginEULADialog</name>
    <message>
        <location filename="../Qt/Core/Resources/UI/pqPluginEULADialog.ui" line="16"/>
        <source>End User License Agreement</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../Qt/Core/Resources/UI/pqPluginEULADialog.ui" line="25"/>
        <source>&lt;!DOCTYPE HTML PUBLIC &quot;-//W3C//DTD HTML 4.0//EN&quot; &quot;http://www.w3.org/TR/REC-html40/strict.dtd&quot;&gt;
&lt;html&gt;&lt;head&gt;&lt;meta name=&quot;qrichtext&quot; content=&quot;1&quot; /&gt;&lt;style type=&quot;text/css&quot;&gt;
p, li { white-space: pre-wrap; }
&lt;/style&gt;&lt;/head&gt;&lt;body style=&quot; font-family:&apos;Sans Serif&apos;; font-size:9pt; font-weight:400; font-style:normal;&quot;&gt;
&lt;p style=&quot; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;&lt;span style=&quot; font-weight:600;&quot;&gt;EULA for plugin&lt;/span&gt;&lt;/p&gt;&lt;/body&gt;&lt;/html&gt;</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>pqAnimationCue</name>
    <message>
        <location filename="../Qt/Core/pqAnimationCue.cxx" line="395"/>
        <source>unrecognized</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>pqAnnotationsModel</name>
    <message>
        <location filename="../Qt/Core/pqAnnotationsModel.cxx" line="301"/>
        <source>Color</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../Qt/Core/pqAnnotationsModel.cxx" line="303"/>
        <source>Opacity</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../Qt/Core/pqAnnotationsModel.cxx" line="346"/>
        <source>Value</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../Qt/Core/pqAnnotationsModel.cxx" line="348"/>
        <source>Annotation</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>pqApplicationCore</name>
    <message>
        <location filename="../Qt/Core/pqApplicationCore.cxx" line="330"/>
        <source>ParaView state file</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../Qt/Core/pqApplicationCore.cxx" line="345"/>
        <source>Python state file</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../Qt/Core/pqApplicationCore.cxx" line="358"/>
        <source>All Files</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../Qt/Core/pqApplicationCore.cxx" line="773"/>
        <source>paraview</source>
        <comment>Cannot set up help engine from %1</comment>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../Qt/Core/pqApplicationCore.cxx" line="828"/>
        <source>Failed to register documentation in %1 via file: %2</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>pqContextView</name>
    <message>
        <location filename="../Qt/Core/pqContextView.cxx" line="252"/>
        <source>Interaction</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>pqCoreConfiguration</name>
    <message>
        <location filename="../Qt/Core/pqCoreConfiguration.cxx" line="39"/>
        <source>Testing specific options</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../Qt/Core/pqCoreConfiguration.cxx" line="43"/>
        <source>Baseline directory where test recorder will store baseline images.</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../Qt/Core/pqCoreConfiguration.cxx" line="47"/>
        <source>Temporary directory used to output test results and other temporary files.</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../Qt/Core/pqCoreConfiguration.cxx" line="51"/>
        <source>Directory containing data files for tests.</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../Qt/Core/pqCoreConfiguration.cxx" line="72"/>
        <source>Test scripts to execute in order specified on the command line.</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../Qt/Core/pqCoreConfiguration.cxx" line="95"/>
        <source>Test baseline for tests script provided.</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../Qt/Core/pqCoreConfiguration.cxx" line="119"/>
        <source>Test image comparison threshold for test scripts provided.</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../Qt/Core/pqCoreConfiguration.cxx" line="124"/>
        <source>Exit application when tests are finished.</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../Qt/Core/pqCoreConfiguration.cxx" line="127"/>
        <source>Test collaboration &apos;master&apos; configuration.</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../Qt/Core/pqCoreConfiguration.cxx" line="129"/>
        <source>Test collaboration &apos;slave&apos; configuration.</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../Qt/Core/pqCoreConfiguration.cxx" line="135"/>
        <source>Options controls actions on application launch</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../Qt/Core/pqCoreConfiguration.cxx" line="137"/>
        <source>State file (.pvsm or .py) to load when the application starts.</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../Qt/Core/pqCoreConfiguration.cxx" line="140"/>
        <source>Python script to execute when the application starts.</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../Qt/Core/pqCoreConfiguration.cxx" line="144"/>
        <source>Load the specified data file(s) when the client starts. To choose a file series, replace the numeral with a &apos;.&apos;, for example,  my0.vtk, my1.vtk...myN.vtk becomes my..vtk, etc.</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../Qt/Core/pqCoreConfiguration.cxx" line="153"/>
        <source>Positional arguments may be used to pass either data (--data), state (--state), or script (--script) files. `.pvsm` files are treated as state files, `.py` are treated as scripts and all others are treated as data files.</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../Qt/Core/pqCoreConfiguration.cxx" line="179"/>
        <source>Connect to Catalyst Live session at the specified port number.</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>pqCoreTestUtility</name>
    <message>
        <location filename="../Qt/Core/pqCoreTestUtility.cxx" line="419"/>
        <source>Cannot read file : %1</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>pqCoreUtilities</name>
    <message>
        <location filename="../Qt/Core/pqCoreUtilities.cxx" line="329"/>
        <source>Yes, and don&apos;t ask again</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../Qt/Core/pqCoreUtilities.cxx" line="335"/>
        <source>OK, and don&apos;t ask again</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../Qt/Core/pqCoreUtilities.cxx" line="537"/>
        <location filename="../Qt/Core/pqCoreUtilities.cxx" line="553"/>
        <source>File IO Warning</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../Qt/Core/pqCoreUtilities.cxx" line="538"/>
        <source>Unable to delete some files in %1</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../Qt/Core/pqCoreUtilities.cxx" line="554"/>
        <source>Unable to delete %1</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>pqFileDialog</name>
    <message>
        <location filename="../Qt/Core/Resources/UI/pqFileDialog.ui" line="16"/>
        <source>Dialog</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../Qt/Core/Resources/UI/pqFileDialog.ui" line="50"/>
        <source>Look in:</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../Qt/Core/Resources/UI/pqFileDialog.ui" line="110"/>
        <source>Toggle file details. This may affect performance for large directories on certain file systems.</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../Qt/Core/Resources/UI/pqFileDialog.ui" line="123"/>
        <source>Toggle file sequence grouping.</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../Qt/Core/Resources/UI/pqFileDialog.ui" line="173"/>
        <source>Favorites</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../Qt/Core/Resources/UI/pqFileDialog.ui" line="186"/>
        <source>Add current directory to favorites</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../Qt/Core/Resources/UI/pqFileDialog.ui" line="206"/>
        <location filename="../Qt/Core/pqFileDialog.cxx" line="710"/>
        <source>Clear favorites</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../Qt/Core/Resources/UI/pqFileDialog.ui" line="249"/>
        <source>Filter favorites panel</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../Qt/Core/Resources/UI/pqFileDialog.ui" line="252"/>
        <source>Filter favorites</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../Qt/Core/Resources/UI/pqFileDialog.ui" line="300"/>
        <source>Locations</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../Qt/Core/Resources/UI/pqFileDialog.ui" line="341"/>
        <source>Recent</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../Qt/Core/Resources/UI/pqFileDialog.ui" line="404"/>
        <location filename="../Qt/Core/pqFileDialog.cxx" line="792"/>
        <source>File name:</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../Qt/Core/Resources/UI/pqFileDialog.ui" line="414"/>
        <source>Files of type:</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../Qt/Core/Resources/UI/pqFileDialog.ui" line="421"/>
        <source>OK</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../Qt/Core/Resources/UI/pqFileDialog.ui" line="431"/>
        <source>Cancel</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../Qt/Core/Resources/UI/pqFileDialog.ui" line="438"/>
        <source>Go to the selected directory, instead of opening it</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../Qt/Core/Resources/UI/pqFileDialog.ui" line="441"/>
        <source>Navigate</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../Qt/Core/pqFileDialog.cxx" line="480"/>
        <source>Local File System</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../Qt/Core/pqFileDialog.cxx" line="484"/>
        <source>Remote File System</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../Qt/Core/pqFileDialog.cxx" line="280"/>
        <source>Navigate Back (%1)</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../Qt/Core/pqFileDialog.cxx" line="293"/>
        <source>Navigate Forward (%1)</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../Qt/Core/pqFileDialog.cxx" line="298"/>
        <source>Navigate Up (%1)</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../Qt/Core/pqFileDialog.cxx" line="302"/>
        <source>Create New Folder (%1)</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../Qt/Core/pqFileDialog.cxx" line="392"/>
        <location filename="../Qt/Core/pqFileDialog.cxx" line="393"/>
        <source>All Files</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../Qt/Core/pqFileDialog.cxx" line="542"/>
        <source>Unable to create directory %1.</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../Qt/Core/pqFileDialog.cxx" line="592"/>
        <source>Add to favorites</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../Qt/Core/pqFileDialog.cxx" line="607"/>
        <source>Rename</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../Qt/Core/pqFileDialog.cxx" line="614"/>
        <source>Open in file explorer</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../Qt/Core/pqFileDialog.cxx" line="632"/>
        <source>Create New Folder</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../Qt/Core/pqFileDialog.cxx" line="644"/>
        <source>Delete empty directory</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../Qt/Core/pqFileDialog.cxx" line="652"/>
        <source>Show Hidden Files</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../Qt/Core/pqFileDialog.cxx" line="711"/>
        <source>This will clear the favorites list.
Are you sure you want to continue ?</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../Qt/Core/pqFileDialog.cxx" line="732"/>
        <source>Remove from favorites</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../Qt/Core/pqFileDialog.cxx" line="737"/>
        <source>Rename label</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../Qt/Core/pqFileDialog.cxx" line="779"/>
        <source>Directory name:</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../Qt/Core/pqFileDialog.cxx" line="786"/>
        <source>Name:</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../Qt/Core/pqFileDialog.cxx" line="802"/>
        <source>open multiple files with &lt;ctrl&gt; key.)</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../Qt/Core/pqFileDialog.cxx" line="803"/>
        <source>open multiple files with &lt;ctrl&gt; key.</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../Qt/Core/pqFileDialog.cxx" line="1508"/>
        <source>%1 already exists.
Do you want to replace it?</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>pqFileDialogFavoriteModel</name>
    <message>
        <location filename="../Qt/Core/pqFileDialogFavoriteModel.cxx" line="267"/>
        <source>Favorites</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>pqFileDialogLocationModel</name>
    <message>
        <location filename="../Qt/Core/pqFileDialogLocationModel.cxx" line="144"/>
        <source>Locations</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>pqFileDialogModel</name>
    <message>
        <location filename="../Qt/Core/pqFileDialogModel.cxx" line="77"/>
        <source>Folder</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../Qt/Core/pqFileDialogModel.cxx" line="84"/>
        <source>File</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../Qt/Core/pqFileDialogModel.cxx" line="101"/>
        <source>%1 TB</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../Qt/Core/pqFileDialogModel.cxx" line="106"/>
        <source>%1 GB</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../Qt/Core/pqFileDialogModel.cxx" line="111"/>
        <source>%1 MB</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../Qt/Core/pqFileDialogModel.cxx" line="116"/>
        <source>%1 KB</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../Qt/Core/pqFileDialogModel.cxx" line="119"/>
        <source>%1 bytes</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../Qt/Core/pqFileDialogModel.cxx" line="801"/>
        <source>Cannot rename to %1, which already exists</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../Qt/Core/pqFileDialogModel.cxx" line="803"/>
        <source>Error renaming</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../Qt/Core/pqFileDialogModel.cxx" line="936"/>
        <source>Group</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../Qt/Core/pqFileDialogModel.cxx" line="1070"/>
        <source>Filename</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../Qt/Core/pqFileDialogModel.cxx" line="1073"/>
        <source>Type</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../Qt/Core/pqFileDialogModel.cxx" line="1076"/>
        <source>Size</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../Qt/Core/pqFileDialogModel.cxx" line="1079"/>
        <source>Date Modified</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>pqFileDialogRecentDirsModel</name>
    <message>
        <location filename="../Qt/Core/pqFileDialogRecentDirsModel.cxx" line="137"/>
        <source>Recent Directories</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>pqIconListModel</name>
    <message>
        <location filename="../Qt/Core/pqIconListModel.h" line="83"/>
        <source>Application resources</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../Qt/Core/pqIconListModel.h" line="84"/>
        <source>User icons</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>pqLinkViewWidget</name>
    <message>
        <location filename="../Qt/Core/pqLinkViewWidget.cxx" line="38"/>
        <source>Click on another view to link with.</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../Qt/Core/pqLinkViewWidget.cxx" line="42"/>
        <source>Name:</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../Qt/Core/pqLinkViewWidget.cxx" line="46"/>
        <source>Interactive View Link</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../Qt/Core/pqLinkViewWidget.cxx" line="48"/>
        <source>Camera Widget View Link</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../Qt/Core/pqLinkViewWidget.cxx" line="65"/>
        <source>Cancel</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../Qt/Core/pqLinkViewWidget.cxx" line="70"/>
        <location filename="../Qt/Core/pqLinkViewWidget.cxx" line="73"/>
        <source>CameraLink%1</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>pqLinksModel</name>
    <message>
        <location filename="../Qt/Core/pqLinksModel.cxx" line="677"/>
        <source>link proxies</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../Qt/Core/pqLinksModel.cxx" line="717"/>
        <source>link cameras in two views</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../Qt/Core/pqLinksModel.cxx" line="854"/>
        <source>link selection between two objects</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../Qt/Core/pqLinksModel.cxx" line="886"/>
        <source>Remove any link given its name</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>pqLogViewerWidget</name>
    <message>
        <location filename="../Qt/Core/pqLogViewerWidget.cxx" line="340"/>
        <source>Save log</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../Qt/Core/pqLogViewerWidget.cxx" line="341"/>
        <source>Text Files</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../Qt/Core/pqLogViewerWidget.cxx" line="341"/>
        <source>All Files</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../Qt/Core/pqLogViewerWidget.cxx" line="355"/>
        <source>Failed to save log to </source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>pqMenuReactionUtils</name>
    <message>
        <location filename="../Qt/Core/pqMenuReactionUtils.cxx" line="46"/>
        <source>Requires an attribute array</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../Qt/Core/pqMenuReactionUtils.cxx" line="47"/>
        <source>Requires a %1 attribute array</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../Qt/Core/pqMenuReactionUtils.cxx" line="53"/>
        <source> with %1 component(s)</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../Qt/Core/pqMenuReactionUtils.cxx" line="63"/>
        <source> or %1</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../Qt/Core/pqMenuReactionUtils.cxx" line="70"/>
        <source>Requirements not met</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>pqMultiSliceAxisWidget</name>
    <message>
        <location filename="../Qt/Core/pqMultiSliceAxisWidget.cxx" line="66"/>
        <source>Default title</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>pqOutputWidget</name>
    <message>
        <location filename="../Qt/Core/pqOutputWidget.cxx" line="438"/>
        <source>Save output</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../Qt/Core/pqOutputWidget.cxx" line="439"/>
        <source>Text Files</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../Qt/Core/pqOutputWidget.cxx" line="439"/>
        <source>All Files</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../Qt/Core/pqOutputWidget.cxx" line="453"/>
        <source>Failed to save output to </source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>pqPluginManager</name>
    <message>
        <location filename="../Qt/Core/pqPluginManager.cxx" line="340"/>
        <source>Accept</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../Qt/Core/pqPluginManager.cxx" line="341"/>
        <source>Decline</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../Qt/Core/pqPluginManager.cxx" line="344"/>
        <source>End User License Agreement for &apos;%1&apos;</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>pqQVTKWidgetEventTranslator</name>
    <message>
        <location filename="../Qt/Core/pqQVTKWidgetEventTranslator.cxx" line="178"/>
        <source>Save Screenshot:</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>pqRenderView</name>
    <message>
        <location filename="../Qt/Core/pqRenderView.cxx" line="829"/>
        <source>create a surface points selection</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../Qt/Core/pqRenderView.cxx" line="845"/>
        <source>create a block selection</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../Qt/Core/pqRenderView.cxx" line="853"/>
        <source>create a surface cells selection</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../Qt/Core/pqRenderView.cxx" line="920"/>
        <source>create a surface points polygon selection</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../Qt/Core/pqRenderView.cxx" line="934"/>
        <source>create a surface cells polygon selection</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../Qt/Core/pqRenderView.cxx" line="967"/>
        <source>create a frustum selection of cells</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../Qt/Core/pqRenderView.cxx" line="1003"/>
        <source>create a frustum selection of points</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../Qt/Core/pqRenderView.cxx" line="1136"/>
        <source>changing interaction mode based on data extents</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>pqRenderViewBase</name>
    <message>
        <location filename="../Qt/Core/pqRenderViewBase.cxx" line="87"/>
        <source>Full resolution render in: %1 s</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>pqScalarBarRepresentation</name>
    <message>
        <location filename="../Qt/Core/pqScalarBarRepresentation.cxx" line="39"/>
        <source>Move Color Legend</source>
        <translation type="unfinished"></translation>
    </message>
</context>
</TS>
