<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS version="2.1" language="zh_CN">
<context>
    <name>LogViewerWidget</name>
    <message>
        <location filename="../Qt/Core/Resources/UI/pqLogViewerWidget.ui" line="16"/>
        <source>Form</source>
        <translation>表单</translation>
    </message>
    <message>
        <location filename="../Qt/Core/Resources/UI/pqLogViewerWidget.ui" line="46"/>
        <source>Set filter on this log</source>
        <translation>在此日志上设置过滤器</translation>
    </message>
    <message>
        <location filename="../Qt/Core/Resources/UI/pqLogViewerWidget.ui" line="56"/>
        <source>Show/hide all columns</source>
        <translation>显示/隐藏所有列</translation>
    </message>
    <message>
        <location filename="../Qt/Core/Resources/UI/pqLogViewerWidget.ui" line="59"/>
        <source>...</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../Qt/Core/Resources/UI/pqLogViewerWidget.ui" line="107"/>
        <source>Select rows above to show raw log text here. Save text with the Export Log button below.</source>
        <translation>在此选择上面的行以显示原始日志文本 。 下面用导出日志按钮保存文本 。</translation>
    </message>
    <message>
        <location filename="../Qt/Core/Resources/UI/pqLogViewerWidget.ui" line="131"/>
        <source>Export Log</source>
        <translation>导出日志</translation>
    </message>
</context>
<context>
    <name>OutputWidget</name>
    <message>
        <location filename="../Qt/Core/Resources/UI/pqOutputWidget.ui" line="16"/>
        <source>Form</source>
        <translation>表单</translation>
    </message>
    <message>
        <location filename="../Qt/Core/Resources/UI/pqOutputWidget.ui" line="73"/>
        <source>Show full messages</source>
        <translation>显示完整消息</translation>
    </message>
    <message>
        <location filename="../Qt/Core/Resources/UI/pqOutputWidget.ui" line="70"/>
        <source>Check to see raw messages generated by the application</source>
        <translation>选中可查看应用程序生成的原始信件</translation>
    </message>
    <message>
        <location filename="../Qt/Core/Resources/UI/pqOutputWidget.ui" line="80"/>
        <source>If unchecked and the window is closed, the window will remain closed when new messages are available.</source>
        <translation>如果未选中且窗口已关闭, 当有新消息可用时, 窗口仍会关闭 。</translation>
    </message>
    <message>
        <location filename="../Qt/Core/Resources/UI/pqOutputWidget.ui" line="83"/>
        <source>Always open for new messages</source>
        <translation>总是打开新信件</translation>
    </message>
    <message>
        <location filename="../Qt/Core/Resources/UI/pqOutputWidget.ui" line="93"/>
        <source>Copy to Clipboard</source>
        <translation>复制到剪贴板</translation>
    </message>
    <message>
        <location filename="../Qt/Core/Resources/UI/pqOutputWidget.ui" line="100"/>
        <source>Save to File...</source>
        <translation>保存到文件...</translation>
    </message>
    <message>
        <location filename="../Qt/Core/Resources/UI/pqOutputWidget.ui" line="107"/>
        <source>Filter Messages</source>
        <translation>过滤信件</translation>
    </message>
    <message>
        <location filename="../Qt/Core/Resources/UI/pqOutputWidget.ui" line="114"/>
        <source>Clear</source>
        <translation>清除</translation>
    </message>
</context>
<context>
    <name>PluginEULADialog</name>
    <message>
        <location filename="../Qt/Core/Resources/UI/pqPluginEULADialog.ui" line="16"/>
        <source>End User License Agreement</source>
        <translation>终止用户许可证协议</translation>
    </message>
    <message>
        <location filename="../Qt/Core/Resources/UI/pqPluginEULADialog.ui" line="25"/>
        <source>&lt;!DOCTYPE HTML PUBLIC &quot;-//W3C//DTD HTML 4.0//EN&quot; &quot;http://www.w3.org/TR/REC-html40/strict.dtd&quot;&gt;
&lt;html&gt;&lt;head&gt;&lt;meta name=&quot;qrichtext&quot; content=&quot;1&quot; /&gt;&lt;style type=&quot;text/css&quot;&gt;
p, li { white-space: pre-wrap; }
&lt;/style&gt;&lt;/head&gt;&lt;body style=&quot; font-family:&apos;Sans Serif&apos;; font-size:9pt; font-weight:400; font-style:normal;&quot;&gt;
&lt;p style=&quot; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;&lt;span style=&quot; font-weight:600;&quot;&gt;EULA for plugin&lt;/span&gt;&lt;/p&gt;&lt;/body&gt;&lt;/html&gt;</source>
        <translation>&lt;!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd"&gt; &lt;html&gt;&lt;head&gt;&lt;meta name="qrichtext" content="1" /&gt;&lt;style type="text/css"&gt;p, li { 白- 空格 : pre- wrap;}&lt;/style&gt;&lt;/head&gt;&lt;body style=" font-family:'Sans Serif'; font-size:9pt; font-weight:400; font-style:normal;"&gt; &lt;p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"&gt;&lt;span style=" font-weight:600;"&gt;插件的 EULA&lt;/span&gt;&lt;/p&gt;&lt;/body&gt;&lt;/html&gt;</translation>
    </message>
</context>
<context>
    <name>pqAnimationCue</name>
    <message>
        <location filename="../Qt/Core/pqAnimationCue.cxx" line="395"/>
        <source>unrecognized</source>
        <translation>未识别</translation>
    </message>
</context>
<context>
    <name>pqAnnotationsModel</name>
    <message>
        <location filename="../Qt/Core/pqAnnotationsModel.cxx" line="301"/>
        <source>Color</source>
        <translation>颜色</translation>
    </message>
    <message>
        <location filename="../Qt/Core/pqAnnotationsModel.cxx" line="303"/>
        <source>Opacity</source>
        <translation>不透明度</translation>
    </message>
    <message>
        <location filename="../Qt/Core/pqAnnotationsModel.cxx" line="346"/>
        <source>Value</source>
        <translation>值</translation>
    </message>
    <message>
        <location filename="../Qt/Core/pqAnnotationsModel.cxx" line="348"/>
        <source>Annotation</source>
        <translation>注释</translation>
    </message>
</context>
<context>
    <name>pqApplicationCore</name>
    <message>
        <location filename="../Qt/Core/pqApplicationCore.cxx" line="330"/>
        <source>ParaView state file</source>
        <translation>ParaView 状态文件</translation>
    </message>
    <message>
        <location filename="../Qt/Core/pqApplicationCore.cxx" line="345"/>
        <source>Python state file</source>
        <translation>Python 状态文件</translation>
    </message>
    <message>
        <location filename="../Qt/Core/pqApplicationCore.cxx" line="358"/>
        <source>All Files</source>
        <translation>所有文件</translation>
    </message>
    <message>
        <location filename="../Qt/Core/pqApplicationCore.cxx" line="773"/>
        <source>paraview</source>
        <comment>Cannot set up help engine from %1</comment>
        <translation>参数</translation>
    </message>
    <message>
        <location filename="../Qt/Core/pqApplicationCore.cxx" line="828"/>
        <source>Failed to register documentation in %1 via file: %2</source>
        <translation>在%1 通过文件注册文档失败 :%2</translation>
    </message>
</context>
<context>
    <name>pqContextView</name>
    <message>
        <location filename="../Qt/Core/pqContextView.cxx" line="252"/>
        <source>Interaction</source>
        <translation>互动</translation>
    </message>
</context>
<context>
    <name>pqCoreConfiguration</name>
    <message>
        <location filename="../Qt/Core/pqCoreConfiguration.cxx" line="39"/>
        <source>Testing specific options</source>
        <translation>测试特定选项</translation>
    </message>
    <message>
        <location filename="../Qt/Core/pqCoreConfiguration.cxx" line="43"/>
        <source>Baseline directory where test recorder will store baseline images.</source>
        <translation>测试记录器将存储基线图像的基准目录 。</translation>
    </message>
    <message>
        <location filename="../Qt/Core/pqCoreConfiguration.cxx" line="47"/>
        <source>Temporary directory used to output test results and other temporary files.</source>
        <translation>用于输出测试结果和其他临时文件的临时目录.</translation>
    </message>
    <message>
        <location filename="../Qt/Core/pqCoreConfiguration.cxx" line="51"/>
        <source>Directory containing data files for tests.</source>
        <translation>包含用于测试的数据文件的目录 。</translation>
    </message>
    <message>
        <location filename="../Qt/Core/pqCoreConfiguration.cxx" line="72"/>
        <source>Test scripts to execute in order specified on the command line.</source>
        <translation>测试要按照命令行指定的顺序执行的脚本。</translation>
    </message>
    <message>
        <location filename="../Qt/Core/pqCoreConfiguration.cxx" line="95"/>
        <source>Test baseline for tests script provided.</source>
        <translation>提供了测试脚本的测试基线.</translation>
    </message>
    <message>
        <location filename="../Qt/Core/pqCoreConfiguration.cxx" line="119"/>
        <source>Test image comparison threshold for test scripts provided.</source>
        <translation>为测试脚本提供测试图像比较阈值.</translation>
    </message>
    <message>
        <location filename="../Qt/Core/pqCoreConfiguration.cxx" line="124"/>
        <source>Exit application when tests are finished.</source>
        <translation>测试完成后退出应用程序 。</translation>
    </message>
    <message>
        <location filename="../Qt/Core/pqCoreConfiguration.cxx" line="127"/>
        <source>Test collaboration &apos;master&apos; configuration.</source>
        <translation>测试协作“ master” 配置 。</translation>
    </message>
    <message>
        <location filename="../Qt/Core/pqCoreConfiguration.cxx" line="129"/>
        <source>Test collaboration &apos;slave&apos; configuration.</source>
        <translation>测试协作“ 奴隶” 配置 。</translation>
    </message>
    <message>
        <location filename="../Qt/Core/pqCoreConfiguration.cxx" line="135"/>
        <source>Options controls actions on application launch</source>
        <translation>应用程序启动时的选项控制动作</translation>
    </message>
    <message>
        <location filename="../Qt/Core/pqCoreConfiguration.cxx" line="137"/>
        <source>State file (.pvsm or .py) to load when the application starts.</source>
        <translation>应用程序启动时要加载的状态文件(.pvsm或.py).</translation>
    </message>
    <message>
        <location filename="../Qt/Core/pqCoreConfiguration.cxx" line="140"/>
        <source>Python script to execute when the application starts.</source>
        <translation>应用程序启动时要执行的 Python 脚本 。</translation>
    </message>
    <message>
        <location filename="../Qt/Core/pqCoreConfiguration.cxx" line="144"/>
        <source>Load the specified data file(s) when the client starts. To choose a file series, replace the numeral with a &apos;.&apos;, for example,  my0.vtk, my1.vtk...myN.vtk becomes my..vtk, etc.</source>
        <translation>客户端启动时装入指定的数据文件 。 要选择文件序列,请将数字替换为'.',例如 my0.vtk, my1.vtk...myN.vtk成为 my.vtk等.</translation>
    </message>
    <message>
        <location filename="../Qt/Core/pqCoreConfiguration.cxx" line="153"/>
        <source>Positional arguments may be used to pass either data (--data), state (--state), or script (--script) files. `.pvsm` files are treated as state files, `.py` are treated as scripts and all others are treated as data files.</source>
        <translation>位置参数可用于传递数据(--data),状态(-state),或脚本(-script)文件. `.pvsm ' 文件被视为国家文件,`.py ' 文件被视为脚本,所有其他文件则被视为数据文件。</translation>
    </message>
    <message>
        <location filename="../Qt/Core/pqCoreConfiguration.cxx" line="179"/>
        <source>Connect to Catalyst Live session at the specified port number.</source>
        <translation>在指定的端口号码上连接到催化剂Live会话.</translation>
    </message>
</context>
<context>
    <name>pqCoreTestUtility</name>
    <message>
        <location filename="../Qt/Core/pqCoreTestUtility.cxx" line="419"/>
        <source>Cannot read file : %1</source>
        <translation>无法读取文件 :%1</translation>
    </message>
</context>
<context>
    <name>pqCoreUtilities</name>
    <message>
        <location filename="../Qt/Core/pqCoreUtilities.cxx" line="329"/>
        <source>Yes, and don&apos;t ask again</source>
        <translation>是的,别再问了</translation>
    </message>
    <message>
        <location filename="../Qt/Core/pqCoreUtilities.cxx" line="335"/>
        <source>OK, and don&apos;t ask again</source>
        <translation>好,别再问了</translation>
    </message>
    <message>
        <location filename="../Qt/Core/pqCoreUtilities.cxx" line="537"/>
        <location filename="../Qt/Core/pqCoreUtilities.cxx" line="553"/>
        <source>File IO Warning</source>
        <translation>文件 IO 警告</translation>
    </message>
    <message>
        <location filename="../Qt/Core/pqCoreUtilities.cxx" line="538"/>
        <source>Unable to delete some files in %1</source>
        <translation>无法删除%1 中的一些文件</translation>
    </message>
    <message>
        <location filename="../Qt/Core/pqCoreUtilities.cxx" line="554"/>
        <source>Unable to delete %1</source>
        <translation>无法删除%1</translation>
    </message>
</context>
<context>
    <name>pqFileDialog</name>
    <message>
        <location filename="../Qt/Core/Resources/UI/pqFileDialog.ui" line="16"/>
        <source>Dialog</source>
        <translation>对话框</translation>
    </message>
    <message>
        <location filename="../Qt/Core/Resources/UI/pqFileDialog.ui" line="50"/>
        <source>Look in:</source>
        <translation>查看内容 :</translation>
    </message>
    <message>
        <location filename="../Qt/Core/Resources/UI/pqFileDialog.ui" line="110"/>
        <source>Toggle file details. This may affect performance for large directories on certain file systems.</source>
        <translation>切换文件细节 。 这可能影响某些文件系统中大目录的性能.</translation>
    </message>
    <message>
        <location filename="../Qt/Core/Resources/UI/pqFileDialog.ui" line="123"/>
        <source>Toggle file sequence grouping.</source>
        <translation>切换文件序列分组 。</translation>
    </message>
    <message>
        <location filename="../Qt/Core/Resources/UI/pqFileDialog.ui" line="173"/>
        <source>Favorites</source>
        <translation>爱好</translation>
    </message>
    <message>
        <location filename="../Qt/Core/Resources/UI/pqFileDialog.ui" line="186"/>
        <source>Add current directory to favorites</source>
        <translation>将当前目录添加到最爱</translation>
    </message>
    <message>
        <location filename="../Qt/Core/Resources/UI/pqFileDialog.ui" line="206"/>
        <location filename="../Qt/Core/pqFileDialog.cxx" line="710"/>
        <source>Clear favorites</source>
        <translation>清除最爱</translation>
    </message>
    <message>
        <location filename="../Qt/Core/Resources/UI/pqFileDialog.ui" line="249"/>
        <source>Filter favorites panel</source>
        <translation>过滤首选面板</translation>
    </message>
    <message>
        <location filename="../Qt/Core/Resources/UI/pqFileDialog.ui" line="252"/>
        <source>Filter favorites</source>
        <translation>过滤器首选</translation>
    </message>
    <message>
        <location filename="../Qt/Core/Resources/UI/pqFileDialog.ui" line="300"/>
        <source>Locations</source>
        <translation>地点</translation>
    </message>
    <message>
        <location filename="../Qt/Core/Resources/UI/pqFileDialog.ui" line="341"/>
        <source>Recent</source>
        <translation>近期</translation>
    </message>
    <message>
        <location filename="../Qt/Core/Resources/UI/pqFileDialog.ui" line="404"/>
        <location filename="../Qt/Core/pqFileDialog.cxx" line="792"/>
        <source>File name:</source>
        <translation>文件名 :</translation>
    </message>
    <message>
        <location filename="../Qt/Core/Resources/UI/pqFileDialog.ui" line="414"/>
        <source>Files of type:</source>
        <translation>类型文件 :</translation>
    </message>
    <message>
        <location filename="../Qt/Core/Resources/UI/pqFileDialog.ui" line="421"/>
        <source>OK</source>
        <translation>确定</translation>
    </message>
    <message>
        <location filename="../Qt/Core/Resources/UI/pqFileDialog.ui" line="431"/>
        <source>Cancel</source>
        <translation>取消</translation>
    </message>
    <message>
        <location filename="../Qt/Core/Resources/UI/pqFileDialog.ui" line="438"/>
        <source>Go to the selected directory, instead of opening it</source>
        <translation>转到选定的目录, 而不是打开它</translation>
    </message>
    <message>
        <location filename="../Qt/Core/Resources/UI/pqFileDialog.ui" line="441"/>
        <source>Navigate</source>
        <translation>导航</translation>
    </message>
    <message>
        <location filename="../Qt/Core/pqFileDialog.cxx" line="480"/>
        <source>Local File System</source>
        <translation>本地文件系统</translation>
    </message>
    <message>
        <location filename="../Qt/Core/pqFileDialog.cxx" line="484"/>
        <source>Remote File System</source>
        <translation>远程文件系统</translation>
    </message>
    <message>
        <location filename="../Qt/Core/pqFileDialog.cxx" line="280"/>
        <source>Navigate Back (%1)</source>
        <translation>返回导航 (%1)</translation>
    </message>
    <message>
        <location filename="../Qt/Core/pqFileDialog.cxx" line="293"/>
        <source>Navigate Forward (%1)</source>
        <translation>前进导航 (%1)</translation>
    </message>
    <message>
        <location filename="../Qt/Core/pqFileDialog.cxx" line="298"/>
        <source>Navigate Up (%1)</source>
        <translation>导航 (%1)</translation>
    </message>
    <message>
        <location filename="../Qt/Core/pqFileDialog.cxx" line="302"/>
        <source>Create New Folder (%1)</source>
        <translation>创建新文件夹 (%1)</translation>
    </message>
    <message>
        <location filename="../Qt/Core/pqFileDialog.cxx" line="392"/>
        <location filename="../Qt/Core/pqFileDialog.cxx" line="393"/>
        <source>All Files</source>
        <translation>所有文件</translation>
    </message>
    <message>
        <location filename="../Qt/Core/pqFileDialog.cxx" line="542"/>
        <source>Unable to create directory %1.</source>
        <translation>无法创建目录%1 。</translation>
    </message>
    <message>
        <location filename="../Qt/Core/pqFileDialog.cxx" line="592"/>
        <source>Add to favorites</source>
        <translation>添加到最爱</translation>
    </message>
    <message>
        <location filename="../Qt/Core/pqFileDialog.cxx" line="607"/>
        <source>Rename</source>
        <translation>重命名</translation>
    </message>
    <message>
        <location filename="../Qt/Core/pqFileDialog.cxx" line="614"/>
        <source>Open in file explorer</source>
        <translation>在文件探索器中打开</translation>
    </message>
    <message>
        <location filename="../Qt/Core/pqFileDialog.cxx" line="632"/>
        <source>Create New Folder</source>
        <translation>创建新文件夹</translation>
    </message>
    <message>
        <location filename="../Qt/Core/pqFileDialog.cxx" line="644"/>
        <source>Delete empty directory</source>
        <translation>删除空目录</translation>
    </message>
    <message>
        <location filename="../Qt/Core/pqFileDialog.cxx" line="652"/>
        <source>Show Hidden Files</source>
        <translation>显示隐藏文件</translation>
    </message>
    <message>
        <location filename="../Qt/Core/pqFileDialog.cxx" line="711"/>
        <source>This will clear the favorites list.
Are you sure you want to continue ?</source>
        <translation>这将清除最爱列表。 你确定你想继续吗?</translation>
    </message>
    <message>
        <location filename="../Qt/Core/pqFileDialog.cxx" line="732"/>
        <source>Remove from favorites</source>
        <translation>从最爱中删除</translation>
    </message>
    <message>
        <location filename="../Qt/Core/pqFileDialog.cxx" line="737"/>
        <source>Rename label</source>
        <translation>重命名标签</translation>
    </message>
    <message>
        <location filename="../Qt/Core/pqFileDialog.cxx" line="779"/>
        <source>Directory name:</source>
        <translation>目录名称 :</translation>
    </message>
    <message>
        <location filename="../Qt/Core/pqFileDialog.cxx" line="786"/>
        <source>Name:</source>
        <translation>名称 :</translation>
    </message>
    <message>
        <location filename="../Qt/Core/pqFileDialog.cxx" line="802"/>
        <source>open multiple files with &lt;ctrl&gt; key.)</source>
        <translation>打开多个文件&lt;ctrl&gt;键。 )</translation>
    </message>
    <message>
        <location filename="../Qt/Core/pqFileDialog.cxx" line="803"/>
        <source>open multiple files with &lt;ctrl&gt; key.</source>
        <translation>打开多个文件&lt;ctrl&gt;键。</translation>
    </message>
    <message>
        <location filename="../Qt/Core/pqFileDialog.cxx" line="1508"/>
        <source>%1 already exists.
Do you want to replace it?</source>
        <translation>%1 已经存在 。 你想替换它吗?</translation>
    </message>
</context>
<context>
    <name>pqFileDialogFavoriteModel</name>
    <message>
        <location filename="../Qt/Core/pqFileDialogFavoriteModel.cxx" line="267"/>
        <source>Favorites</source>
        <translation>爱好</translation>
    </message>
</context>
<context>
    <name>pqFileDialogLocationModel</name>
    <message>
        <location filename="../Qt/Core/pqFileDialogLocationModel.cxx" line="144"/>
        <source>Locations</source>
        <translation>地点</translation>
    </message>
</context>
<context>
    <name>pqFileDialogModel</name>
    <message>
        <location filename="../Qt/Core/pqFileDialogModel.cxx" line="77"/>
        <source>Folder</source>
        <translation>文件夹</translation>
    </message>
    <message>
        <location filename="../Qt/Core/pqFileDialogModel.cxx" line="84"/>
        <source>File</source>
        <translation>文件</translation>
    </message>
    <message>
        <location filename="../Qt/Core/pqFileDialogModel.cxx" line="101"/>
        <source>%1 TB</source>
        <translation>%1 肺结核</translation>
    </message>
    <message>
        <location filename="../Qt/Core/pqFileDialogModel.cxx" line="106"/>
        <source>%1 GB</source>
        <translation>%1 个GB</translation>
    </message>
    <message>
        <location filename="../Qt/Core/pqFileDialogModel.cxx" line="111"/>
        <source>%1 MB</source>
        <translation>%1 MB 数据</translation>
    </message>
    <message>
        <location filename="../Qt/Core/pqFileDialogModel.cxx" line="116"/>
        <source>%1 KB</source>
        <translation>%1 个 KB</translation>
    </message>
    <message>
        <location filename="../Qt/Core/pqFileDialogModel.cxx" line="119"/>
        <source>%1 bytes</source>
        <translation>%1 字节</translation>
    </message>
    <message>
        <location filename="../Qt/Core/pqFileDialogModel.cxx" line="801"/>
        <source>Cannot rename to %1, which already exists</source>
        <translation>无法重命名到已经存在的%1 。</translation>
    </message>
    <message>
        <location filename="../Qt/Core/pqFileDialogModel.cxx" line="803"/>
        <source>Error renaming</source>
        <translation>重命名出错</translation>
    </message>
    <message>
        <location filename="../Qt/Core/pqFileDialogModel.cxx" line="936"/>
        <source>Group</source>
        <translation>组</translation>
    </message>
    <message>
        <location filename="../Qt/Core/pqFileDialogModel.cxx" line="1070"/>
        <source>Filename</source>
        <translation>文件名</translation>
    </message>
    <message>
        <location filename="../Qt/Core/pqFileDialogModel.cxx" line="1073"/>
        <source>Type</source>
        <translation>类型</translation>
    </message>
    <message>
        <location filename="../Qt/Core/pqFileDialogModel.cxx" line="1076"/>
        <source>Size</source>
        <translation>大小</translation>
    </message>
    <message>
        <location filename="../Qt/Core/pqFileDialogModel.cxx" line="1079"/>
        <source>Date Modified</source>
        <translation>修改日期</translation>
    </message>
</context>
<context>
    <name>pqFileDialogRecentDirsModel</name>
    <message>
        <location filename="../Qt/Core/pqFileDialogRecentDirsModel.cxx" line="137"/>
        <source>Recent Directories</source>
        <translation>最近的目录</translation>
    </message>
</context>
<context>
    <name>pqIconListModel</name>
    <message>
        <location filename="../Qt/Core/pqIconListModel.h" line="83"/>
        <source>Application resources</source>
        <translation>应用程序资源</translation>
    </message>
    <message>
        <location filename="../Qt/Core/pqIconListModel.h" line="84"/>
        <source>User icons</source>
        <translation>用户图标</translation>
    </message>
</context>
<context>
    <name>pqLinkViewWidget</name>
    <message>
        <location filename="../Qt/Core/pqLinkViewWidget.cxx" line="38"/>
        <source>Click on another view to link with.</source>
        <translation>点击另一个视图链接 。</translation>
    </message>
    <message>
        <location filename="../Qt/Core/pqLinkViewWidget.cxx" line="42"/>
        <source>Name:</source>
        <translation>名称 :</translation>
    </message>
    <message>
        <location filename="../Qt/Core/pqLinkViewWidget.cxx" line="46"/>
        <source>Interactive View Link</source>
        <translation>交互式视图链接</translation>
    </message>
    <message>
        <location filename="../Qt/Core/pqLinkViewWidget.cxx" line="48"/>
        <source>Camera Widget View Link</source>
        <translation>相机部件查看链接</translation>
    </message>
    <message>
        <location filename="../Qt/Core/pqLinkViewWidget.cxx" line="65"/>
        <source>Cancel</source>
        <translation>取消</translation>
    </message>
    <message>
        <location filename="../Qt/Core/pqLinkViewWidget.cxx" line="70"/>
        <location filename="../Qt/Core/pqLinkViewWidget.cxx" line="73"/>
        <source>CameraLink%1</source>
        <translation>相机链接%1</translation>
    </message>
</context>
<context>
    <name>pqLinksModel</name>
    <message>
        <location filename="../Qt/Core/pqLinksModel.cxx" line="677"/>
        <source>link proxies</source>
        <translation>链接代理</translation>
    </message>
    <message>
        <location filename="../Qt/Core/pqLinksModel.cxx" line="717"/>
        <source>link cameras in two views</source>
        <translation>在两个视图中连接相机</translation>
    </message>
    <message>
        <location filename="../Qt/Core/pqLinksModel.cxx" line="854"/>
        <source>link selection between two objects</source>
        <translation>链接两个对象之间的选择</translation>
    </message>
    <message>
        <location filename="../Qt/Core/pqLinksModel.cxx" line="886"/>
        <source>Remove any link given its name</source>
        <translation>删除其名称的任何链接</translation>
    </message>
</context>
<context>
    <name>pqLogViewerWidget</name>
    <message>
        <location filename="../Qt/Core/pqLogViewerWidget.cxx" line="340"/>
        <source>Save log</source>
        <translation>保存日志</translation>
    </message>
    <message>
        <location filename="../Qt/Core/pqLogViewerWidget.cxx" line="341"/>
        <source>Text Files</source>
        <translation>文本文件</translation>
    </message>
    <message>
        <location filename="../Qt/Core/pqLogViewerWidget.cxx" line="341"/>
        <source>All Files</source>
        <translation>所有文件</translation>
    </message>
    <message>
        <location filename="../Qt/Core/pqLogViewerWidget.cxx" line="355"/>
        <source>Failed to save log to </source>
        <translation>保存日志到失败</translation>
    </message>
</context>
<context>
    <name>pqMenuReactionUtils</name>
    <message>
        <location filename="../Qt/Core/pqMenuReactionUtils.cxx" line="46"/>
        <source>Requires an attribute array</source>
        <translation>需要属性数组</translation>
    </message>
    <message>
        <location filename="../Qt/Core/pqMenuReactionUtils.cxx" line="47"/>
        <source>Requires a %1 attribute array</source>
        <translation>需要%1 属性数组</translation>
    </message>
    <message>
        <location filename="../Qt/Core/pqMenuReactionUtils.cxx" line="53"/>
        <source> with %1 component(s)</source>
        <translation>带有%1 组件</translation>
    </message>
    <message>
        <location filename="../Qt/Core/pqMenuReactionUtils.cxx" line="63"/>
        <source> or %1</source>
        <translation>或%1 个</translation>
    </message>
    <message>
        <location filename="../Qt/Core/pqMenuReactionUtils.cxx" line="70"/>
        <source>Requirements not met</source>
        <translation>未满足的要求</translation>
    </message>
</context>
<context>
    <name>pqMultiSliceAxisWidget</name>
    <message>
        <location filename="../Qt/Core/pqMultiSliceAxisWidget.cxx" line="66"/>
        <source>Default title</source>
        <translation>默认标题</translation>
    </message>
</context>
<context>
    <name>pqOutputWidget</name>
    <message>
        <location filename="../Qt/Core/pqOutputWidget.cxx" line="438"/>
        <source>Save output</source>
        <translation>保存输出</translation>
    </message>
    <message>
        <location filename="../Qt/Core/pqOutputWidget.cxx" line="439"/>
        <source>Text Files</source>
        <translation>文本文件</translation>
    </message>
    <message>
        <location filename="../Qt/Core/pqOutputWidget.cxx" line="439"/>
        <source>All Files</source>
        <translation>所有文件</translation>
    </message>
    <message>
        <location filename="../Qt/Core/pqOutputWidget.cxx" line="453"/>
        <source>Failed to save output to </source>
        <translation>保存输出到失败</translation>
    </message>
</context>
<context>
    <name>pqPluginManager</name>
    <message>
        <location filename="../Qt/Core/pqPluginManager.cxx" line="340"/>
        <source>Accept</source>
        <translation>接受</translation>
    </message>
    <message>
        <location filename="../Qt/Core/pqPluginManager.cxx" line="341"/>
        <source>Decline</source>
        <translation>缩写</translation>
    </message>
    <message>
        <location filename="../Qt/Core/pqPluginManager.cxx" line="344"/>
        <source>End User License Agreement for &apos;%1&apos;</source>
        <translation>“%1” 的结束用户许可协议</translation>
    </message>
</context>
<context>
    <name>pqQVTKWidgetEventTranslator</name>
    <message>
        <location filename="../Qt/Core/pqQVTKWidgetEventTranslator.cxx" line="178"/>
        <source>Save Screenshot:</source>
        <translation>保存屏幕截图 :</translation>
    </message>
</context>
<context>
    <name>pqRenderView</name>
    <message>
        <location filename="../Qt/Core/pqRenderView.cxx" line="829"/>
        <source>create a surface points selection</source>
        <translation>创建表面点选择</translation>
    </message>
    <message>
        <location filename="../Qt/Core/pqRenderView.cxx" line="845"/>
        <source>create a block selection</source>
        <translation>创建块选择</translation>
    </message>
    <message>
        <location filename="../Qt/Core/pqRenderView.cxx" line="853"/>
        <source>create a surface cells selection</source>
        <translation>创建表面单元格选择</translation>
    </message>
    <message>
        <location filename="../Qt/Core/pqRenderView.cxx" line="920"/>
        <source>create a surface points polygon selection</source>
        <translation>创建表面点多边形选择</translation>
    </message>
    <message>
        <location filename="../Qt/Core/pqRenderView.cxx" line="934"/>
        <source>create a surface cells polygon selection</source>
        <translation>创建表面单元格多边形选择</translation>
    </message>
    <message>
        <location filename="../Qt/Core/pqRenderView.cxx" line="967"/>
        <source>create a frustum selection of cells</source>
        <translation>创建单元格的frustum选择</translation>
    </message>
    <message>
        <location filename="../Qt/Core/pqRenderView.cxx" line="1003"/>
        <source>create a frustum selection of points</source>
        <translation>创建点的节点选择</translation>
    </message>
    <message>
        <location filename="../Qt/Core/pqRenderView.cxx" line="1136"/>
        <source>changing interaction mode based on data extents</source>
        <translation>根据数据范围改变交互模式</translation>
    </message>
</context>
<context>
    <name>pqRenderViewBase</name>
    <message>
        <location filename="../Qt/Core/pqRenderViewBase.cxx" line="87"/>
        <source>Full resolution render in: %1 s</source>
        <translation>完全解析渲染于 :%1 s</translation>
    </message>
</context>
<context>
    <name>pqScalarBarRepresentation</name>
    <message>
        <location filename="../Qt/Core/pqScalarBarRepresentation.cxx" line="39"/>
        <source>Move Color Legend</source>
        <translation>移动颜色图例</translation>
    </message>
</context>
</TS>
